### ISSUE TITLE
大神，我想重新用webpack打包，但是 Module build failed: Error: Cannot find module '@babel/core'

### ISSUE THREAD

**Issue by alun1** [chxj1992/kline#56]
ERROR in ./src/entry.js
    Module build failed: Error: Cannot find module '@babel/core'
        at Function.Module._resolveFilename (module.js:547:15)
        at Function.Module._load (module.js:474:25)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\Administrator\workspace\kline-master\nod
e_modules\babel-loader\lib\transform.js:1:75)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\Administrator\workspace\kline-master\nod
e_modules\babel-loader\lib\cache.js:24:17)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\Administrator\workspace\kline-master\nod
e_modules\babel-loader\lib\index.js:9:13)
        at Module._compile (module.js:652:30)
        at Object.Module._extensions..js (module.js:663:10)
        at Module.load (module.js:565:32)
        at tryModuleLoad (module.js:505:12)
        at Function.Module._load (module.js:497:3)
        at Module.require (module.js:596:17)
        at require (internal/module.js:11:18)
        at loadLoader (C:\Users\Administrator\workspace\kline-master\node_module
s\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (C:\Users\Administrator\workspace\kline-master
\node_modules\loader-runner\lib\LoaderRunner.js:169:2)

**Comment by alun1** [comment]
刚从Android转过来，不明白这是什么

**Comment by alun1** [comment]
babel-core 是装好的
